# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='设备名称')),
                ('own_group', models.CharField(max_length=5000, verbose_name='归属小组')),
                ('current_process', models.CharField(default='##闲置OR使用##', max_length=5000, verbose_name='当前使用状态')),
                ('occupied_by', models.CharField(default='#使用人更新#', max_length=200, verbose_name='当前使用人')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='概要')),
                ('detail', models.CharField(max_length=5000, verbose_name='详细描述')),
                ('current_process', models.CharField(default='##由改进实施人填写##', max_length=5000, verbose_name='处理进展')),
                ('value', models.CharField(max_length=200, verbose_name='改进价值评估')),
                ('reviewer', models.CharField(default='#提交人填写#', max_length=200, verbose_name='改进建议评审人')),
                ('executor', models.CharField(default='#由建议评审人指派#', max_length=200, verbose_name='改进建议实施人')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
