# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecardmodel',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='设备描述'),
        ),
    ]
