# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiantMaintainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='QQ昵称')),
                ('device_info', models.CharField(choices=[('TCR', (('TCR 圆点', 'TCR 圆点'), ('TCR 环意粉', 'TCR 环意粉'), ('TCR SL', 'TCR SL'), ('TCR Pro Disc', 'TCR Pro Disc'), ('TCR Pro Team', 'TCR Pro Team'), ('TCR Pro 0', 'TCR Pro 0'), ('TCR Pro 1', 'TCR Pro 1'), ('TCR ADV 1', 'TCR ADV 1'), ('TCR ADV 2', 'TCR ADV 2'), ('TCR ADV 3', 'TCR ADV 3'), ('TCR 6700', 'TCR 6700'), ('TCR 6300', 'TCR 6300'))), ('Propel', (('Propel ADV 1', 'Propel ADV 1'), ('Propel ADV 2', 'Propel ADV 2'), ('Propel ADV 3', 'Propel ADV 3'))), ('XTC', (('XTC ADV 1', 'XTC ADV 1'), ('XTC ADV 2', 'XTC ADV 2'), ('XTC ADV 3', 'XTC ADV 3'), ('XTC SLR', 'XTC SLR'), ('XTC 880', 'XTC 880'), ('XTC 860', 'XTC 860'), ('XTC 820', 'XTC 820'), ('XTC 800', 'XTC 800'))), ('ATX', (('ATX 850', 'ATX 850'), ('ATX 700', 'ATX 700'), ('ATX 610', 'ATX 610'))), ('误操作', '误操作'), ('配置', '配置')], max_length=2000, verbose_name='车辆型号')),
                ('assigned_to', models.CharField(default='anyone', max_length=200, verbose_name='分配给(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
    ]
