# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('urgency', models.CharField(max_length=200)),
                ('current_process', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=200)),
                ('curent_state', models.CharField(max_length=200)),
            ],
        ),
    ]
