# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171123_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='giantmaintainmodel',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=2000, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='giantmaintainmodel',
            name='custom_name',
            field=models.CharField(default='##请在此输入真实姓名##', max_length=200, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='giantmaintainmodel',
            name='order_type',
            field=models.CharField(choices=[('维修调试', '维修调试'), ('例行保养', '例行保养')], default=datetime.datetime(2017, 11, 23, 10, 29, 25, 922763, tzinfo=utc), max_length=2000, verbose_name='预约类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giantmaintainmodel',
            name='weixin',
            field=models.CharField(default=datetime.datetime(2017, 11, 23, 10, 29, 45, 300676, tzinfo=utc), max_length=200, verbose_name='微信号'),
            preserve_default=False,
        ),
    ]
