# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170906_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemodel',
            name='processer_1st',
            field=models.CharField(default='', max_length=200, verbose_name='hahaha'),
        ),
        migrations.AddField(
            model_name='namemodel',
            name='processer_2nd',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='namemodel',
            name='processer_3rd',
            field=models.CharField(default='', max_length=200),
        ),
    ]
