# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namemodel',
            name='processer_1st',
        ),
        migrations.AddField(
            model_name='namemodel',
            name='created_by',
            field=models.CharField(default='', max_length=200, verbose_name='创建人'),
        ),
    ]
