# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_ess_supplyspportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESS_LeftBugSolveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='项目')),
                ('content', models.CharField(max_length=5000, verbose_name='主要工作内容')),
                ('responser', models.CharField(default='0', max_length=200, verbose_name='负责人')),
                ('responser_to_maitain', models.CharField(default='0', max_length=200, verbose_name='转维负责人')),
                ('deadline', models.CharField(default='0', max_length=200, verbose_name='完成日期')),
                ('current_process', models.CharField(default='##在此更新进展##', max_length=5000, verbose_name='当前进展')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
        migrations.CreateModel(
            name='ESS_MasterBranchSyncModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='项目')),
                ('content', models.CharField(max_length=5000, verbose_name='主要工作内容')),
                ('responser', models.CharField(default='0', max_length=200, verbose_name='负责人')),
                ('responser_to_maitain', models.CharField(default='0', max_length=200, verbose_name='转维负责人')),
                ('deadline', models.CharField(default='0', max_length=200, verbose_name='完成日期')),
                ('current_process', models.CharField(default='##在此更新进展##', max_length=5000, verbose_name='当前进展')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
        migrations.AlterField(
            model_name='ess_customerissuemodel',
            name='current_process',
            field=models.CharField(default='##在此更新进展##', max_length=5000, verbose_name='当前进展'),
        ),
        migrations.AlterField(
            model_name='ess_ordersupportmodel',
            name='current_process',
            field=models.CharField(default='##在此更新进展##', max_length=5000, verbose_name='当前进展'),
        ),
        migrations.AlterField(
            model_name='ess_supplyspportmodel',
            name='current_process',
            field=models.CharField(default='##在此更新进展##', max_length=5000, verbose_name='当前进展'),
        ),
    ]
