# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170921_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namemodel',
            name='priority',
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='assigned_to',
            field=models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='created_by',
            field=models.CharField(default='', max_length=200, verbose_name='创建人(只读)'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='curent_state',
            field=models.CharField(max_length=200, verbose_name='当前状态(只读)'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='current_process',
            field=models.CharField(max_length=5000, verbose_name='处理进展'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='detail',
            field=models.CharField(max_length=5000, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
