# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20171227_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerReleaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='版本号')),
                ('commit_id', models.CharField(max_length=200, verbose_name='git_commit_id')),
                ('release_date', models.DateField(default=django.utils.timezone.now, max_length=2000, verbose_name='发布日期')),
                ('build_info', models.CharField(default='##此处填写构建信息，可从上一个版本拷贝进行修改GG##', max_length=9000, verbose_name='构建信息')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
    ]
