# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_verreleasemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verreleasemodel',
            name='assigned_to',
            field=models.CharField(default='anyone', max_length=200, verbose_name='当前处理人(只读)'),
        ),
        migrations.AlterField(
            model_name='verreleasemodel',
            name='build_info',
            field=models.CharField(default='##此处填写构建信息，可从上一个版本拷贝进行修改##', max_length=9000, verbose_name='构建信息'),
        ),
    ]
