# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_verreleasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetrackmodel',
            name='file',
            field=models.FileField(default='111', upload_to='./'),
            preserve_default=False,
        ),
    ]
