# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170921_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namemodel',
            old_name='processer_2nd',
            new_name='reviewer',
        ),
    ]
