# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170921_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemodel',
            name='executor',
            field=models.CharField(default='', max_length=200, verbose_name='改进建议实施人'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='current_process',
            field=models.CharField(default='##由改进实施人填写##', max_length=5000, verbose_name='处理进展'),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='reviewer',
            field=models.CharField(default='', max_length=200, verbose_name='改进建议评审人'),
        ),
    ]
