# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_issuetrackmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetrackmodel',
            old_name='file',
            new_name='attachedfile',
        ),
    ]
