# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180116_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='attachedfile',
            field=models.FileField(upload_to='../../../djangofile', verbose_name='附件'),
        ),
    ]
