# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180117_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodolistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='概要')),
                ('detail', models.CharField(max_length=5000, verbose_name='详细描述')),
                ('current_process', models.CharField(default='##此处填写进展##', max_length=5000, verbose_name='处理进展')),
                ('assigned_to', models.CharField(default='', max_length=200, verbose_name='当前处理人(只读)')),
                ('created_by', models.CharField(default='', max_length=200, verbose_name='创建人(只读)')),
                ('curent_state', models.CharField(max_length=200, verbose_name='当前状态(只读)')),
            ],
        ),
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='attachedfile',
            field=models.FileField(blank=True, null=True, upload_to='djangofile/', verbose_name='附件'),
        ),
    ]
