# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180122_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='class_1',
            field=models.CharField(choices=[('软件', '软件'), ('硬件', '硬件'), ('结构', '结构'), ('误操作', '误操作'), ('配置', '配置'), ('兼容性', '兼容性'), ('沟通协作', '沟通协作')], max_length=200, verbose_name='问题大类'),
        ),
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='class_2',
            field=models.CharField(choices=[('软件', (('FC', 'FC'), ('SAS', 'SAS'), ('固件', '固件'), ('压缩', '压缩'))), ('硬件', (('内存', '内存'), ('板卡', '板卡'), ('线缆', '线缆'))), ('误操作', '误操作'), ('结构', '结构'), ('配置', '配置'), ('兼容性', '兼容性'), ('沟通协作', '沟通协作')], max_length=200, verbose_name='问题小类'),
        ),
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='class_3',
            field=models.CharField(choices=[('软件', (('FC', 'FC'), ('SAS', 'SAS'), ('固件', '固件'), ('压缩', '压缩'))), ('硬件', (('内存', '内存'), ('板卡', '板卡'), ('线缆', '线缆')))], max_length=200, verbose_name='责任领域'),
        ),
        migrations.AlterField(
            model_name='issuetrackmodel',
            name='customer_type',
            field=models.CharField(choices=[('jinrong', '金融'), ('dianli', '电力'), ('nengyuan', '能源'), ('guangdian', '广电'), ('meizi', '媒资'), ('tezhong', '特种行业'), ('neibu', '内部客户'), ('其他', '其他')], max_length=200, verbose_name='客户类别'),
        ),
    ]
