# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180323_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='verreleasemodel',
            name='prj_name',
            field=models.CharField(choices=[('OAK', 'OAK'), ('Bamboo', 'Bamboo')], default=django.utils.timezone.now, max_length=100, verbose_name='项目'),
            preserve_default=False,
        ),
    ]
